apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kartograph-stage
resources:
  - ../../base
  - route.yaml
  - secret-provider-class.yaml
patches:
  - path: configmap-patch.yaml
  - path: resources-patch.yaml
  - path: deployment-vault-patch.yaml
images:
  - name: quay.io/redhat-user-workloads/kartograph-tenant/kartograph-api
    newTag: 1.1.0
