apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kartograph-stage
resources:
  - ../../base
  - route.yaml
patches:
  - path: configmap-patch.yaml
  - path: resources-patch.yaml
images:
  - name: quay.io/redhat-user-workloads/kartograph-tenant/kartograph-api
    newTag: 9c7601918968f432256b80631d90a505d460931b
