apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kartograph-stage
resources:
  - ../../base
  - route.yaml
  - dev-ui-route.yaml
patches:
  - path: configmap-patch.yaml
  - path: resources-patch.yaml
images:
  - name: quay.io/redhat-user-workloads/kartograph-tenant/kartograph-api
    newTag: 0a925cbfacb73f09c6d2d19488ce05be56d09d3b
  - name: quay.io/redhat-user-workloads/kartograph-tenant/kartograph-dev-ui
    newTag: 462dfcdfb47f9b0695d43859518387357c947d25
