apiVersion: v1
kind: Service
metadata:
  name: kartograph-dev-ui
  labels:
    app.kubernetes.io/component: dev-ui
spec:
  selector:
    app.kubernetes.io/component: dev-ui
  ports:
    - name: http
      port: 3000
      targetPort: 3000
