apiVersion: batch/v1
kind: Job
metadata:
  name: kartograph-db-migrate
  labels:
    app.kubernetes.io/component: database-migrate
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database-migrate
    spec:
      restartPolicy: OnFailure
      initContainers:
        # Wait for db-init job to complete
        - name: wait-for-db-init
          image: groundnuty/k8s-wait-for:v7.0
          imagePullPolicy: IfNotPresent
          args:
            - "job"
            - "kartograph-db-init"
      containers:
        - name: migrate
          image: quay.io/redhat-user-workloads/kartograph-tenant/kartograph-api:latest
          imagePullPolicy: IfNotPresent
          command:
            - alembic
            - upgrade
            - head
          env:
            - name: KARTOGRAPH_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: kartograph-config
                  key: KARTOGRAPH_DB_HOST
            - name: KARTOGRAPH_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: kartograph-config
                  key: KARTOGRAPH_DB_PORT
            - name: KARTOGRAPH_DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kartograph-config
                  key: KARTOGRAPH_DB_DATABASE
            - name: KARTOGRAPH_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kartograph-config
                  key: KARTOGRAPH_DB_USERNAME
            - name: KARTOGRAPH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kartograph-db-credentials
                  key: password
